### PR TITLE
Misc fixes to descriptions and class spell lists

### PR DESCRIPTION
**Pull request by austinreadhoff**
Parts of Command, Enhance Ability, and Enlarge/Reduce were missing

### CODE REVIEW

**Comment by austinreadhoff** [comment]
Found a number of other spells with missing chunks of their descriptions as well.  In the process of transcribing, and will push to this pull request when done.

**Comment by austinreadhoff** [comment]
That should do be all of them

**Comment by austinreadhoff** [comment]
Found some more bugs in which classes get which spells.  Will update.

**Comment by austinreadhoff** [comment]
Ok, NOW that should be all of them :)

**Review by vorpalhex — APPROVED** [review]

**Pull request merged**
